//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class assign
    {
        [DisplayName("Paper ID")]
        public int paper_id { get; set; }

        [DisplayName("Reviewer ID")]
        public string reviewer_id { get; set; }

        [DisplayName("Note")]
        public string aaa { get; set; }
        
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual paper paper { get; set; }
    }
}
