//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Conf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conf()
        {
            this.paper = new HashSet<paper>();
        }

        [DisplayName("Conference ID")]
        public int Id { get; set; }

        [DisplayName("Conference Name")]
        [Required]
        public string name { get; set; }

        [DisplayName("Keyword")]
        [Required]
        public string topic { get; set; }

        [DisplayName("Chair ID")]
        public string chair_id { get; set; }

        [DisplayName("Paper Submission Deadline")]
        public Nullable<System.DateTime> sub_deadline { get; set; }

        [DisplayName("Review Deadline")]
        public Nullable<System.DateTime> rev_deadline { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paper> paper { get; set; }
    }
}
