//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class paper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paper()
        {
            this.assign = new HashSet<assign>();
            this.paperkey = new HashSet<paperkey>();
            this.review = new HashSet<review>();
        }

        [DisplayName("Paper ID")]
        public int Id { get; set; }

        [DisplayName("Title")]
        [MaxLength(50)]
        [Required]
        public string title { get; set; }

        [DisplayName("Content")]
        [Required]
        [MaxLength(256)]
        public string body { get; set; }

        [DisplayName("Is assigned?")]
        public bool assigned { get; set; }

        [DisplayName("Is accespted?")]
        public bool accepted { get; set; }

        [DisplayName("User ID")]
        public string user_id { get; set; }

        [DisplayName("Conference ID")]
        [Required]
        public int conf_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assign> assign { get; set; }
        public virtual Conf Conf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paperkey> paperkey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> review { get; set; }
    }
}
