//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class review
    {
        [DisplayName("Review ID")]
        public int Id { get; set; }

        [DisplayName("rating")]
        [Required]
        [Range(0,5)]
        public int rating { get; set; }

        [DisplayName("Comment")]
        [Required]
        public string comment { get; set; }

        [DisplayName("User ID")]
        public string user_id { get; set; }

        [DisplayName("Paper ID")]
        public int paper_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual paper paper { get; set; }
    }
}
